### ISSUE TITLE
Feature Request: Movable ilvl number text within the gear icon.

### ISSUE THREAD

**Issue by Ookami313** [kemayo/wow-simpleitemlevel#11]
Requesting the ability to move the position of the ilvl number text in the gear icon field? Currently it is positioning itself in the upper right of the item icon which ends up over lapping the informational symbol for addons such as Can I Mog It. The ability to move the ilvl number to other positions in the gear/item icon would be helpful. Thanks.

**Comment by kemayo** [comment]
I'd say this is done for now. Major enhancement I could imagine would be customizing it by type-of-button, but that's more complexity in configuration than I want to take on right now so I'll wait to see if people actually ask for it.
