### ISSUE TITLE
Dont show i-lvl in Bags with litebag

### ISSUE THREAD

**Issue by Vilogity** [kemayo/wow-simpleitemlevel#14]
2x ItemLevelDisplay/Bags.lua:94: attempt to index local 't' (a nil value)
[string "@ItemLevelDisplay/Bags.lua"]:94: in function `GetInfo'
[string "@ILD-Litebag/core.lua"]:8: in function `Display'
[string "@ILD-Litebag/core.lua"]:5: in function `f'
[string "@LiteBag/Hooks.lua"]:28: in function `CallHooks'
[string "@LiteBag/ContainerPanel.lua"]:650: in function `UpdateItems'
[string "@FrameXML/ContainerFrame.lua"]:985: in function <FrameXML/ContainerFrame.lua:983>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:82: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:74>
[string "=(tail call)"]: ?
[string "@FrameXML/ContainerFrame.lua"]:983: in function `AddItemsForRefresh'
[string "@FrameXML/ContainerFrame.lua"]:993: in function `Update'
[string "@LiteBag/ContainerPanel.lua"]:230: in function `GenerateFrame'
[string "@LiteBag/ContainerPanel.lua"]:144: in function <LiteBag/ContainerPanel.lua:141>
[string "=[C]"]: in function `SetShown'
[string "@LiteBag/Frame.lua"]:165: in function <LiteBag/Frame.lua:160>

**Comment by Vilogity** [comment]
SRY wrong addon

**Comment by kemayo** [comment]
Wrong addon -- this looks like it's a bug report for [this one](https://www.curseforge.com/wow/addons/itemleveldisplay).

**Comment by kemayo** [comment]
Heh, jinx. :D

**Comment by Vilogity** [comment]
yes........
