### ISSUE TITLE
Item level isn't fitting into the available space in some languages in Retail.

### ISSUE THREAD

**Issue by anyuta1166** [kemayo/wow-simpleitemlevel#19]
Item level isn't fitting into the available space in some languages in Retail.

Inspect frame:

![изображение](https://user-images.githubusercontent.com/726409/207365551-50b39653-7381-4e70-a1ed-cf8f4d97075b.png)

Character frame:

![изображение](https://user-images.githubusercontent.com/726409/207365600-254f0958-d9f4-415c-87dc-05a2046cfdb1.png)

**Comment by anyuta1166** [comment]
Also there is no reason to display item level on character frame in Retail since it's already displayed in the default UI.

**Comment by kemayo** [comment]
Hm, are you using a git checkout of this? It should only be showing up if it thinks we're in a "debug" mode, which I currently have set up as "this hasn't gone through the packager".

**Comment by kemayo** [comment]
I'll change that to a hidden config setting, I suppose.

**Comment by anyuta1166** [comment]
> Hm, are you using a git checkout of this? It should only be showing up if it thinks we're in a "debug" mode, which I currently have set up as "this hasn't gone through the packager".

I've downloaded the addon from Curseforge.

The addon version is v26 and here is the line in addon.lua: `ns.DEBUG = GetAddOnMetadata(myname, "Version") == "v26"`

**Comment by kemayo** [comment]
Hah, okay! I overlooked something very silly -- the packager is transforming the version in my check as well. Embarrassing. :D

**Comment by anyuta1166** [comment]
So you intended to hide the item level display on the character frame, okay.
But the inspect frame still doesn't fit the item level string.

**Comment by kemayo** [comment]
I will fix that, too. I only didn't earlier because the maintenance was still happening.

**Comment by kemayo** [comment]
Okay, should be better now.
