### ISSUE TITLE
Wrong item level displayed for pets

### ISSUE THREAD

**Issue by tflo** [kemayo/wow-simpleitemlevel#20]
For battle pets, it shows "20" as level, no matter if it's level 1 or level 25.

**Comment by kemayo** [comment]
This one is actually kind of interesting, and is because of how Blizzard implements caged pets. *Technically* all caged pets are item 82800, "Pet Cage", which is item level 20.

I can probably special-case this one so it knows about caged pets and extracts their level rather than the cage.

**Comment by tflo** [comment]
Thank you!
