### ISSUE TITLE
Does not show pet levels if used with Bagnon

### ISSUE THREAD

**Issue by tflo** [kemayo/wow-simpleitemlevel#24]
The two most recent versions do not show the pet levels with Bagnon (bags or bank), they work fine though with LiteBag or Blizz's addon. Levels of "other" items are shown.

The last version that shows pet levels with Bagnon is `v27-1-g9bd26f9`.

**Comment by kemayo** [comment]
A thing I did to fix an error in void storage for bagnon caused the caged pets to get skipped.
