### ISSUE TITLE
LUA error when logging in

### ISSUE THREAD

**Issue by Hemario** [kemayo/wow-simpleitemlevel#25]
```
39x SimpleItemLevel/addon.lua:205: attempt to compare number with nil
[string "@SimpleItemLevel/addon.lua"]:205: in function <SimpleItemLevel/addon.lua:195>
[string "@SimpleItemLevel/addon.lua"]:669: in function <SimpleItemLevel/addon.lua:669>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:35: in function <FrameXML/ObjectAPI/AsyncCallbackSystem.lua:31>
```
Only have it when I start the game and log in the first time, not when I /releadui and only on 1 character.

**Comment by kemayo** [comment]
Interesting. I can add some guardrails around that.

I'm curious which bag addon you're using, though -- this error happening right on login should only happen when those buttons are being displayed.

**Comment by Hemario** [comment]
I was indeed trying out several bag add-ons to see which one fit me. At the time of the error, I was using ArkInventory.

In the meantime, I switched to AdiBags and I have not yet seen the error.

**Comment by nancikennedy** [comment]
I switched to Bagnon yesterday, and am getting this same error when 1st logging into a character as well. Reloading makes it go away.

64x SimpleItemLevel/addon.lua:205: attempt to compare number with nil
[string "@SimpleItemLevel/addon.lua"]:205: in function <SimpleItemLevel/addon.lua:195>
[string "@SimpleItemLevel/addon.lua"]:669: in function <SimpleItemLevel/addon.lua:669>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:35: in function <FrameXML/ObjectAPI/AsyncCallbackSystem.lua:31>

**Comment by kemayo** [comment]
Should be avoided with aa9cf50f334863c3a55ea11418b820f36714e9e2
