### ISSUE TITLE
api changes 9.0 beta

### ISSUE THREAD

**Issue by agentschmitt** [kemayo/wow-simpleitemlevel#3]
hey i have tested the addon on shadowlands beta 9.0 and got some lua error in line 156
`quality >= LE_ITEM_QUALITY_UNCOMMON and (`
must be changed to
`quality >= Enum.ItemQuality.Uncommon and (`

didn´t get any other errors, but if there are more here are the api changes
https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes

**Comment by kemayo** [comment]
I've got a private branch for the changes already (actually, I thought I'd pushed it up, but I guess not) -- I'm just waiting for the prepatch so I can release things.

**Comment by agentschmitt** [comment]
Hi i have tested the shadowlands branch on beta and it works pretty well :)
But the support for baggins is removed in this branch. Could you add this again? https://github.com/kemayo/wow-simpleitemlevel/pull/2

**Comment by kemayo** [comment]
Fair point, I was going to wait until before release to merge it in, but I don't mind doing it now. I've done a rebase and pushed it up.
