### ISSUE TITLE
Baganator hook: UnifiedBags --> UnifiedViews

### ISSUE THREAD

**Issue by tflo** [kemayo/wow-simpleitemlevel#32]
As of Baganator 173-7-g1e5deb6 [it's Unified**Views**](https://github.com/plusmouse/Baganator/commit/4606e6685a5ec7d834e0f3aa0e2e6d8e7da9e25c):

```diff
diff --git a/SimpleItemLevel/addon.lua b/SimpleItemLevel/addon.lua
--- a/SimpleItemLevel/addon.lua
+++ b/SimpleItemLevel/addon.lua
@@ -677,5 +677,5 @@
     if Baganator_MainViewFrame then
         baganator_hookmain()
-    elseif Baganator and Baganator.UnifiedBags.Initialize then
-        hooksecurefunc(Baganator.UnifiedBags, "Initialize", baganator_hookmain)
+    elseif Baganator and Baganator.UnifiedViews.Initialize then
+        hooksecurefunc(Baganator.UnifiedViews, "Initialize", baganator_hookmain)
     end
```

**Comment by kemayo** [comment]
It's a little more complicated than just that -- d795dddea7bf0717587a29dc72ec1d159d13c713 changed the names of some frames, too.

**Comment by tflo** [comment]
Maybe even more; since my post he released two more versions it seems.

**Comment by kemayo** [comment]
The curse of (a) a fast-moving addon, and (b) me not having just ported this to use its API yet.

**Comment by kemayo** [comment]
Anyway, I have a basic fix right now. It has an issue with the reagent bank, but I'll look at that in more detail later.
