### ISSUE TITLE
API for item level text

### ISSUE THREAD

**Issue by Cidan** [kemayo/wow-simpleitemlevel#39]
Having an API to return colorized item level text would work really well for integrations. Ideally, the call would take an ItemLink as a parameter, and return a string with the colored item level.

**Comment by kemayo** [comment]
How does `SimpleItemLevel.API.ItemLevelColorized(itemOrItemLink) => "item level wrapped in color codes"` seem?

**Comment by Cidan** [comment]
Absolutely perfect :)
