### ISSUE TITLE
LibItemLevel-1.0 missing in Release7

### ISSUE THREAD

**Issue by agentschmitt** [kemayo/wow-simpleitemlevel#4]
the LibItemLevel-1.0 is missing in Release7 and results in a lua error

**Comment by kemayo** [comment]
Looks like I removed the actual usage of the library back in 5ee2b0dc64fea39be4eb525b6e7764b01992f1ff but forgot to strip the reference from `embeds.xml`. Everything should be working apart from WoW complaining about a missing file.
