### ISSUE TITLE
Performance issue with Baganator due to Baganator API behaviour change

### ISSUE THREAD

**Issue by plusmouse** [kemayo/wow-simpleitemlevel#44]
Hi.

On ` Mon Jun 10 11:50:06 2024 +0100` I made a change to the Baganator corner widgets APIs so that when `nil` is returned from the callback it calls the callback again until it gets a true or false.

This change was so that if any item data was missing, or the widget was delayed initialisation due to budgeting to avoid a frame rate lag it could let the Baganator API trigger a rerequest later, and then fall back to the other widgets in the priority order if actually there was nothing to display.

To fix the performance issue add a `return false` at the end of the callback if you don't want the widget to be displayed. This is addition to the already existing `return true` found in the code.

**Comment by kemayo** [comment]
Thanks for letting me know, I will update these calls as-needed!

**Comment by kemayo** [comment]
Okay, I think that should cover it.

**Comment by plusmouse** [comment]
Awesome. Thanks :)
