### ISSUE TITLE
Display wrongly persists in warband bank after changing to "buy" tab

### ISSUE THREAD

**Issue by mbattersby** [kemayo/wow-simpleitemlevel#45]
E.g.,

![image](https://github.com/user-attachments/assets/eaf9e55a-e578-45e8-86b9-4b8c00463f64)
![image](https://github.com/user-attachments/assets/095a5b7c-e4fe-478e-8c86-9b0b121a2945)

**Comment by kemayo** [comment]
Amusingly, this is part me and part Blizzard. Note that *with SimpleItemLevels disabled*, you still get the tooltips for the items when you mouse over where they're hidden.

**Comment by mbattersby** [comment]
The warbank is all kinds of buggy. GG bliz.

**Comment by mbattersby** [comment]
FWIW I logged this https://github.com/Stanzilla/WoWUIBugs/issues/619
