### ISSUE TITLE
Lua error with the newest Cata Classic version

### ISSUE THREAD

**Issue by Pocokk** [kemayo/wow-simpleitemlevel#46]
38x SimpleItemLevel/addon.lua:192: attempt to call field 'IsBoundToAccountUntilEquip' (a nil value)
[string "@SimpleItemLevel/addon.lua"]:192: in function <SimpleItemLevel/addon.lua:178>
[string "@SimpleItemLevel/addon.lua"]:356: in function <SimpleItemLevel/addon.lua:353>
[string "=[C]"]: in function `xpcall'
[string "@Blizzard_ObjectAPI/Classic/Item.lua"]:298: in function `FireCallbacks'
[string "@Blizzard_ObjectAPI/Classic/Item.lua"]:260: in function <Blizzard_ObjectAPI/Classic/Item.lua:256>
[string "=[C]"]: ?
[string "=[C]"]: in function `RequestLoadItemDataByID'
[string "@Blizzard_ObjectAPI/Classic/Item.lua"]:274: in function `AddCallback'
[string "@Blizzard_ObjectAPI/Classic/Item.lua"]:238: in function `ContinueOnItemLoad'
[string "@SimpleItemLevel/addon.lua"]:353: in function <SimpleItemLevel/addon.lua:348>
[string "@SimpleItemLevel/addon.lua"]:552: in function <SimpleItemLevel/addon.lua:542>
[string "@SimpleItemLevel/addon.lua"]:770: in function <SimpleItemLevel/addon.lua:756>
...
[string "@BagBrother/core/classes/itemGroup.lua"]:32: in function `Update'
[string "@BagBrother/core/classes/itemGroup.lua"]:26: in function <BagBrother/core/classes/itemGroup.lua:12>
[string "=(tail call)"]: ?
[string "@Bagnon/src/frame.lua"]:24: in function `New'
[string "@BagBrother/core/api/frames.lua"]:83: in function `New'
[string "@BagBrother/core/core.lua"]:42: in function <BagBrother/core/core.lua:42>
[string "=[C]"]: ?
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BagBrother/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
item = <table> {
 GetItemLocation = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:66
 SetItemLink = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:56
 HasItemLocation = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:70
 LockItem = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:113
 itemLocation = <table> {
 }
 GetItemID = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:98
 IsItemDataCached = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:216
 GetInventoryTypeName = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:210
 GetCurrentItemLevel = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:172
 GetItemQualityColor = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:183
 UnlockItem = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:119
 Clear = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:74
 GetItemIcon = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:125
 IsItemLocked = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:109
 GetItemLink = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:146
 SetItemLocation = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:51
 GetItemName = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:135
 IsItemInPlayersControl = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:92
 GetItemQuality = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:161
 GetItemGUID = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:199
 GetInventoryType = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:188
 IsItemEmpty = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:80
 GetStaticBackingItem = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:88
 SetItemID = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:61
 IsDataEvictable = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:227
 ContinueWithCancelOnItemLoad = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:242
 ContinueOnItemLoad = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:233
}
details = <table> {
 missingGems = false
 missingEnchants = true
 link = "|cff1eff00|Hitem:55567::::::-133:1820459241:85:::::::::|h[Talondeep Bracers of the Stormblast]|h|r"
 level = 312
 quality = 2
}
itemLocation = <table> {
 Clear = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:21
 IsEquipmentSlot = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:48
 IsEqualToBagAndSlot = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:60
 SetBagAndSlot = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:27
 IsBagAndSlot = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:52
 SetEquipmentSlot = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:38
 HasAnyLocation = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:56
 slotIndex = 6
 GetEquipmentSlot = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:44
 IsEqualToEquipmentSlot = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:68
 bagID = 2
 GetBagAndSlot = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:34
 IsEqualTo = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:76
}
(*temporary) = nil
(*temporary) = <table> {
 Clear = <function> defined @Blizzard_ObjectAPI/Classic/ItemLocation.lua:21
 IsEquipmentSlot = <function> defined @Blizzard_O

**Comment by kemayo** [comment]
Thanks, should be fixed now!

**Comment by Pocokk** [comment]
Thank you for the quick fix!
