### ISSUE TITLE
Addon fail to fetch items

### ISSUE THREAD

**Issue by bbmasters** [kemayo/wow-simpleitemlevel#9]
**Upon inspecting a new player** the addon fails to fetch the items.
Resulting in that I have to "inspect" the same player twice, before showing the ilvls.

1st inspect = https://i.imgur.com/STbBbZE.png
2nd inspect = https://i.imgur.com/WlSssIH.png

**Comment by kemayo** [comment]
Hm, I'll have to look into what events are available to indicate the data has actually arrived.

**Comment by kemayo** [comment]
There's an alpha up from 01d5ce0 which might make this more reliable. You're doing this in Wrath, right?

**Comment by kemayo** [comment]
Confirming that this is only an issue in classic. I think I have a fix, though.
